sonar.projectKey=CristianMz21_prescriptions-app-backend
sonar.organization=cristianmz21

sonar.sources=src
sonar.tests=test

sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Buena práctica: Excluir tests y reportes del análisis de código fuente
sonar.exclusions=dist/**,node_modules/**,coverage/**,**/*.spec.ts,**/*.e2e-spec.ts

sonar.sourceEncoding=UTF-8
