# Required metadata
sonar.projectKey=prescriptions-api
sonar.projectName=Prescriptions Management API MVP
sonar.projectVersion=1.0

# Path to the source code (relative to where the scanner runs)
sonar.sources=src

# Language specification
sonar.language=ts
sonar.profile=node

# Exclusions to keep metrics clean and focused on production code
# Excludes compiled output, modules, tests, and database migrations from duplication/coverage checks
sonar.exclusions=node_modules/**, dist/**, **/*.spec.ts, **/*.e2e-spec.ts, prisma/migrations/**, prisma/generated/**

# Path to tests
sonar.tests=src,test
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts

# Linter and Coverage reports paths (if jest coverage is configured)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.scanner.skipJreProvisioning=false
