%%{init: {"theme": "base", "themeVariables": {"fontSize": "16px"}}}%%
erDiagram
    USER {
        string id PK
        string email UK
        string passwordHash
        enum role "ADMIN|DOCTOR|PATIENT"
        datetime createdAt
        datetime updatedAt
    }

    PRESCRIPTION {
        string id PK
        enum status "PENDING|CONSUMED"
        string notes
        datetime createdAt
        datetime updatedAt
        string doctorId FK
        string patientId FK
    }

    PRESCRIPTION_ITEM {
        string id PK
        string name
        string dosage
        int quantity
        string instructions
        datetime createdAt
        string prescriptionId FK
    }

    USER ||--o{ PRESCRIPTION : "doctor"
    USER ||--o{ PRESCRIPTION : "patient"
    PRESCRIPTION ||--o{ PRESCRIPTION_ITEM : "items"